### ISSUE TITLE
John 2022 TODO

### ISSUE THREAD

**Issue by mariospapaz** [mariospapaz/JohnsAdventure#66]
- [ ] fix .git being extremely bloated
- [ ] experiment by compressing images and audio
- [ ] fix boss bug
- [ ] clean what's possible without damage
